version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-restaurante
    environment:
      POSTGRES_DB: RESTAURANTE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: juan
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d RESTAURANTE"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: juan0407/restaurante-app:latest
    container_name: springboot-restaurante
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9595:9595"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RESTAURANTE
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: juan
    volumes:
      - ./src/main/resources/static/images:/app/static/images

volumes:
  postgres_data:
