spring.application.name=restaurante

# Deja estas propiedades por defecto; Docker las sobrescribirá con la sección 'environment' del Compose
spring.datasource.url=jdbc:postgresql://localhost:5432/RESTAURANTE
spring.datasource.username=postgres
spring.datasource.password=juan

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=9595
# ELIMINADO: Quita 'server.address=localhost' para que Docker pueda redirigir el puerto hacia afuera

# CAMBIADO: Usa la ruta interna del contenedor que mapeaste en el volumen del Compose
imagenes.directorio=/app/static/images/
spring.web.resources.static-locations=classpath:/static/
